print("train_set[0]:      shape={}\t dtype={}".format(train_set[0].shape, train_set[0].dtype))
print("train_set[1]:      shape={}\t dtype={}".format(train_set[1].shape, train_set[1].dtype))
print("validation_set[0]: shape={}\t dtype={}".format(validation_set[0].shape, validation_set[0].dtype))
print("validation_set[1]: shape={}\t dtype={}".format(validation_set[1].shape, validation_set[1].dtype))
print("test_set[0]:       shape={}\t dtype={}".format(test_set[0].shape, test_set[0].dtype))
print("test_set[1]:       shape={}\t dtype={}".format(test_set[1].shape, test_set[1].dtype))